### ISSUE TITLE
Install fails on Mac with Apple Silicon chip

### ISSUE THREAD

**Issue by Panzenbaby** [PayvoHQ/wallet#259]
I tried to install the wallet on my Mac with Apple Silicon chip. Unfortunately I got an error:

`HTTPError: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v9.2.0/electron-v9.2.0-darwin-arm64.zip`

I read that the error is caused by the missing Apple Silicon support of electron. They added support in 11.0.0-beta1.
Maybe you could update the dependencies? 

I tried to simply update the electron dependency by myself but that lead me into some runtime errors.

Many thanks for any help!

**Comment by faustbrian** [comment]
Electron will be updated to to 14.0 shortly before release to ensure we have the latest security and compatibility patches available to us.

**Comment by faustbrian** [comment]
https://github.com/PayvoHQ/wallet/issues/280
