### ISSUE TITLE
Payvo Alpha Known Issues List

### ISSUE THREAD

**Issue by samharperpittam** [PayvoHQ/wallet#406]
The Payvo Wallet will be released to the ARK community via Discord for a public Alpha test phase on Tuesday the 19th of October. Below is a list of known issues that are actively being tracked and worked on. Please read this list before submitting a new issue. 

- Various maintenance & stability tasks
- Multisignature stability issues when used on the Lisk network.
- Multisignature stability issues when used on the Compendia network.
- Improve UX for encryption password during Create and Import wallets.
- Improve UX for encryption password when 2nd Signature is present or when registering for 2nd Signature if it's previously set.
- Implement auto-detect if the wallet has 2nd Signature on wallet Import.
- Improve user feedback during Profile Import (https://github.com/PayvoHQ/wallet/pull/459)
- Network Icons can have different order based on action (ie, Send Transaction or Wallet Import) (https://github.com/PayvoHQ/wallet/pull/421)
- Multipayment transactions show an incorrect "Return" icon at all times (https://github.com/PayvoHQ/wallet/pull/425)
- Currently unable to remove a password from a profile when set. (https://github.com/PayvoHQ/wallet/pull/477)
- Table sorting improvements.
- 'Learn More' links currently do not resolve to the correct documentation.
- The Payvo Wallet Documentation is currently incomplete.

**Comment by alesmit** [comment]
@samharperpittam is there any item in this list that hasn't been fixed yet?

**Comment by samharperpittam** [comment]
> @samharperpittam is there any item in this list that hasn't been fixed yet?

I believe the only remaining issues are related to documentation links so it's not a big deal and I'll create a new task later with the correct links. I'm going to close this issue now. Thanks.
