### ISSUE TITLE
[Routing] Keep all routes as enum constants

### ISSUE THREAD

**Issue by ignromanov** [PayvoHQ/wallet#435]
1. Collect all routes used and represent them with a set of enum constants. 
2. Use the built-in react-router functions to fill in the route parameters and compare routes.

Before:
```
const sendTransferPath = `/profiles/${profile?.id()}/send-transfer`;
```
After:
```
// routing lib
export enum ProfilePathes =  { 
    SendTransfer: '/profiles/:id/send-transfer',
    ...
}

// usage
const sendTransferPath = generatePath(ProfilePathes.SendTransfer, { id: profile?.id() });

```

****

Benefits: 
- routing paths will be unified, 
- the problem of inconsistency of the used paths in different parts of the application will disappear,
- to replace part of the path address, you only need to replace the address in the constants,
- parameter substitution  in the path will be unified through the appropriate library

**Comment by alfonsobries** [comment]
Refactored here https://github.com/PayvoHQ/wallet/pull/856/files
