### ISSUE TITLE
[Typing] Separate implementations of types and components 

### ISSUE THREAD

**Issue by ignromanov** [PayvoHQ/wallet#436]
Now interfaces, types and components are usually mixed in one file with the component definition.
 
This creates code-reading problems, unnecessarily increases component file size, and circular dependencies if types are used by other components.

It is necessary to separate data types and move all type definitions into separate files with the extension `.contracts.`

**Comment by alesmit** [comment]
@ignromanov @faustbrian can this be closed in favor of https://github.com/PayvoHQ/wallet/issues/494?

**Comment by faustbrian** [comment]
Would close it and turn #494 into a task list.
