### ISSUE TITLE
[Wallets Listing] Move "Star" and "Secondary Signature" indicators out of Wallet Type column.

### ISSUE THREAD

**Issue by samharperpittam** [PayvoHQ/wallet#445]
In list view, we show the Star and the Secondary Signature under the "Wallet Type". These are indicators rather than types. So, these star icons and the secondary signature icon should be displayed against the wallet address in the wallet address column.

![image](https://user-images.githubusercontent.com/44671015/138658061-0e910818-a558-40fb-8c47-d7e45701d59d.png)

**Comment by alesmit** [comment]
Closing due to issue not affecting the new design.
