### ISSUE TITLE
[Table Sorting] Sorting should sort the entire data available in the tables rather than the visible data.

### ISSUE THREAD

**Issue by samharperpittam** [PayvoHQ/wallet#450]
**Bug description (high-level overview)**
When the user attempts to sort any column, the app sorts only the visible content of the table.

**What it should do (intended behaviour)**
The app should sort the entire data available in the table.

**What it does instead (bug behaviour)**
The app is not sorting the entire data available in the table. Only the visible content is getting sorted.

**Steps to reproduce (be thorough)**
Navigate to any tabular content with pagination.
Attempt to sort the content on any column.
We'll notice that only the visible contents are sorted.

Please refer to the attached video for better understanding.

https://user-images.githubusercontent.com/44671015/138662771-77e7862c-d8cc-4ed0-9fe4-16b403f5ea0c.mov

**Comment by w3ea** [comment]
tables that affected:

- walletsList

- pluginList 

- delegate table
