### ISSUE TITLE
[Lisk musig] The transaction details shows "Invalid Date" in the date column

### ISSUE THREAD

**Issue by anil203** [PayvoHQ/wallet#467]
The date field shows "Invalid Date" for Lisk musig transactions

![Screenshot 2021-10-27 at 12 54 14 PM](https://user-images.githubusercontent.com/10047242/139019321-d4b54a0e-c9cb-4196-af96-347571afdcc7.png)

**Comment by samharperpittam** [comment]
The timestamp is now displayed correctly.
