### ISSUE TITLE
Notifications dropdown is always empty for LISK and BIND mainnet.

### ISSUE THREAD

**Issue by anil203** [PayvoHQ/wallet#491]
When the user enables only mainnet wallets, the notification drop down does not show any notifications for the transactions performed using the corresponding wallets.
<img width="1017" alt="Screenshot 2021-10-29 at 3 59 32 PM" src="https://user-images.githubusercontent.com/10047242/139419998-bbea332a-9b72-4a08-809d-1d4a528bf0af.png">

**Comment by alesmit** [comment]
@anil203 @w3ea can this be closed?
