### ISSUE TITLE
[Wallet Filters] The sequence of networks in the wallet filters is not consistent for Public/Mainnet and development networks.

### ISSUE THREAD

**Issue by anil203** [PayvoHQ/wallet#502]
The sequence of filters for Public/Mainnet network is: ARK - LISK - BIND - QREDIT

Whereas the filters sequence for development network is DARK - TBIND - LISK - QREDIT

We need to make the sequence of filters for Public/Mainnet networks consistent and match with the sequence of development network.

![Screenshot 2021-11-01 at 2 11 18 PM](https://user-images.githubusercontent.com/10047242/139645892-eb77f232-7895-4e61-b953-3f0d80b30c27.png)

**Comment by w3ea** [comment]
also on vote page
![Screenshot 2021-11-02 112130](https://user-images.githubusercontent.com/24996341/139825124-4ce203c5-6122-4850-9024-2741f680dd53.png)
