### ISSUE TITLE
[Encryption] adjust import/create wallet flow to conditionally display encryption step 

### ISSUE THREAD

**Issue by dated** [PayvoHQ/wallet#506]
The `Create Wallet` and `Import Wallet` flows should both feature a new toggle which controls whether or not the Wallet Encryption step is shown or not. Activating and deactivating the toggle will increase and decrese the step count at the top accordingly.

### Import Wallet
The toggle should be placed on the Import Type step. The toggle will be disabled for import types that do not allow encryption, such as `Address` and `Public Key`. After clicking on `Continue` the wallet checks if the Wallet has registered a second signature. If that is the case the Wallet Encryption step will feature an additional input field for the second mnemonic/secret. Both mnemonics/secrets will be encrypted with the same password.

### Create Wallet
The toggle should be placed on the Passphrase step.

**Comment by alesmit** [comment]
@dated regarding this point:
> Activating and deactivating the toggle will increase and decrease the step count at the top accordingly.

I want to make it clear that if the user decides not to enable encryption but their wallet has the 2nd signature there will still be an extra step after they click on `Continue`. For example, if step count is 3 or 4 depending on whether encryption is disabled or enabled, if the wallet has a 2nd signature, the step count will always end up being 4, leading to not matching the user's expectation.

What if, in the same step, we check that the wallet has a 2nd signature only upon verifying that the mnemonic is valid? This way we could make the field show up below and keep the Encryption step as-is just with the password input.
