### ISSUE TITLE
Update React Hook Form to `7.x`

### ISSUE THREAD

**Issue by goga-m** [PayvoHQ/wallet#546]
RHF v7 introduces changes in the way fields are registering/unregistering that will possibly impact functionality in all existing form structures and flows, especially those with steps that have conditional rendering. An update to v7 will require to thoroughly test existing forms and make sure existing functionality is intact - tests such as checking fields have the expected value when moving back and forth in transaction form steps.

**Comment by faustbrian** [comment]
https://www.react-hook-form.com/migrate-v6-to-v7/ for reference

**Comment by alesmit** [comment]
After v7.12.2 RHF introduced a bug that prevents objects with a prototype from being used as values for form fields. Therefore the majority of our forms using instances of `Networks.Network` or `IReadWriteWallet` stopped working. The RHF lead maintainer does not seem to be willing to fix this issue, for reference: https://github.com/react-hook-form/react-hook-form/issues/6704.

We're considering migrating to [Formik](https://github.com/formium/formik), for now we'll just close this issue and keep RHF v6.
