### ISSUE TITLE
Implement deep linking

### ISSUE THREAD

**Issue by goga-m** [PayvoHQ/wallet#751]
Consider adding URL handling support to replace electrons deep linking functionality.

For PWA URL handling: https://web.dev/pwa-url-handler/

**Comment by faustbrian** [comment]
If this is solely for PWA we can close this for now

**Comment by goga-m** [comment]
:+1:

**Comment by goga-m** [comment]
Closing it https://github.com/PayvoHQ/wallet/issues/800

**Comment by faustbrian** [comment]
The only reason to keep it in WW alone as a website is if we can actually link to the website with the `payvo:` URIs.

**Comment by goga-m** [comment]
@faustbrian renamed this task to reflect url handling for send transfer. https://github.com/PayvoHQ/wallet/issues/800
