### ISSUE TITLE
Handle idle time checks

### ISSUE THREAD

**Issue by goga-m** [PayvoHQ/wallet#753]
Replace previously used `electron.remote.powerMonitor.getSystemIdleTime()` in https://github.com/PayvoHQ/web-wallet/blob/web/src/utils/electron-utils.ts#L31 to check whether the system exceeded idle time.

**Comment by w3ea** [comment]
handle multiple tabs/windows

https://user-images.githubusercontent.com/24996341/148952940-30e008d1-dac3-4e97-9be6-be24bf5e3e89.mp4
