### ISSUE TITLE
[SEND Transaction] Unable to perform a send transaction using the send option on wallet homepage.

### ISSUE THREAD

**Issue by anil203** [PayvoHQ/wallet#817]
Using the send option on the top right corner of the wallet homepage, the user is not able to perform a send transaction. After selection on the crypto asset, the "Continue" button is still disabled.

Steps to reproduce:
1. Login to profile.
2. Select the "SEND" (arrow) button on the top right corner of the wallet homepage.
3. Select the crypto asset from follow up screen.

We'll notice that the "Continue" button is still disabled after selection of the crypto asset.

https://user-images.githubusercontent.com/10047242/149920665-1054ec8c-19c8-49f2-bd14-67578c0bad7f.mp4

**Comment by alfonsobries** [comment]
@anil203 should be fixed here https://github.com/PayvoHQ/wallet/pull/824
