### ISSUE TITLE
[Create Wallet] mnemonic download incorrect toast message

### ISSUE THREAD

**Issue by alfonsobries** [PayvoHQ/wallet#827]
When user creates a new wallet and download his mnemonic passphrase the toast notification shows the path placeholder instead of the path

![image](https://user-images.githubusercontent.com/17262776/150036124-94d44774-5780-465e-bf84-8a301eaab26b.png)

Steps to reproduce:

- Create a new wallet
- in the mnemonic step press download
- see toast notification

Attached video in case you need more details

https://user-images.githubusercontent.com/17262776/150036340-cfe19f40-7bb9-42bd-b84d-e4cb6a0683ff.mov

**Comment by anil203** [comment]
The toast is not displayed on Firefox and Safari browsers

**Comment by dated** [comment]
That is correct, since they use the legacy save dialog we cannot tell if the actual download did happen or not, so we cannot properly react to such event.
