### ISSUE TITLE
Run E2E tests against chrome, edge and firefox

### ISSUE THREAD

**Issue by faustbrian** [PayvoHQ/wallet#857]
Create separate CI jobs that run the E2E against chrome, edge and firefox.

**Comment by alfonsobries** [comment]
Firefox tests https://github.com/PayvoHQ/wallet/pull/904

Still needs edge tests

**Comment by faustbrian** [comment]
@alfonsobries if possible also run them against safari but I'm not sure if that is possible without running E2E locally on a machine that has safari installed.
