### ISSUE TITLE
[Multisignature Registration] Fee stays grayed out

### ISSUE THREAD

**Issue by boldninja** [PayvoHQ/wallet#859]
Steps to reproduce:

- Open one of the wallets on Devnet that has balance in
- Dot menu -> Multisignature
- See the 'Transaction Fee' field

When you try to register a multisignature the TX Fee field stays grayed out and the error icon is present ('Fee required'). It doesn't matter if you add participants or not you cannot move on from that step forward.

**Comment by alfonsobries** [comment]
Should be fixed once [this is released](https://github.com/PayvoHQ/sdk/pull/702) and deps updated
