### ISSUE TITLE
[Multisignature Registration] Change dropdown text

### ISSUE THREAD

**Issue by samharperpittam** [PayvoHQ/wallet#860]
The Multisignature Participant field currently states "Select option". This should be changed to "Address" to match other similar fields throughout the wallet. 

![image](https://user-images.githubusercontent.com/44671015/150510112-a12dca34-83ab-478f-a73a-0bf8d1356699.png)

**Comment by alfonsobries** [comment]
PR. https://github.com/PayvoHQ/wallet/pull/872
