### ISSUE TITLE
[Profile Page] dot menu on hover should use different color

### ISSUE THREAD

**Issue by boldninja** [PayvoHQ/wallet#861]
**Problem**

On 'Profile Page' at the moment the on-hover color for the dot menu is red, which we don't use anymore.

![3dotmenu](https://user-images.githubusercontent.com/25795454/150523149-56d808f1-66cb-4e8a-b3bc-59722c493673.png)

**Solution**

Colors for this should be:

**_- Green Theme (Light)_** 
Normal state - Green300
Hover state - Green400

**_- Blue Theme (Light)_**
Normal state - Blue300
Hover State - Blue400

**_- Dark theme (All)_**
Normal State  - Gray600
Hover State - Gray200

Any other on-hover that still uses this red should also be changed to reflect the above-mentioned color scheme.

**Comment by alfonsobries** [comment]
PR https://github.com/PayvoHQ/wallet/pull/871
