### ISSUE TITLE
[Create Wallet] Redesign Copy/Download section

### ISSUE THREAD

**Issue by boldninja** [PayvoHQ/wallet#864]
**Current Design**

![current-password](https://user-images.githubusercontent.com/25795454/150581126-f3171d77-1763-4c34-bcfa-97df717239af.png)

**New Design**

![copyordownload](https://user-images.githubusercontent.com/25795454/150581842-e5e769fd-285f-4319-a5de-1c8c18ccbb3f.png)

- Title is now 'Copy or Download Mnemonic' so that it will better fit responsive design
- Copy and Download are now links on the left instead of the buttons on the right (old design)
- Gray background to highlight this area from the pack

**Comment by alfonsobries** [comment]
PR https://github.com/PayvoHQ/wallet/pull/870/files
