### ISSUE TITLE
[Create Profile] Styling issue when selecting browser suggested names

### ISSUE THREAD

**Issue by samharperpittam** [PayvoHQ/wallet#866]
When creating a profile using Chrome, the user may be able to select a suggested name via their browser. When selecting the suggested name, this causes a styling error if the user's wallet is in Dark Mode. 

See video below

https://user-images.githubusercontent.com/44671015/150763467-f064b8ab-86b2-4243-9c86-d956c1136ed2.mov

At this moment in time I have only tested with Chrome. I shall test on other Browsers and update this issue. 

This is also an issue for Password fields too:
![image](https://user-images.githubusercontent.com/44671015/150769009-60bb2c74-ea3f-453c-b025-3b2c4629ba66.png)

I suggest we completely disable any form of browser styling.

**Comment by alfonsobries** [comment]
Fixed here https://github.com/PayvoHQ/wallet/pull/869
