### ISSUE TITLE
[Create / Import] Blockpool Errors

### ISSUE THREAD

**Issue by samharperpittam** [PayvoHQ/wallet#875]
Attempting to create or import a wallet on the Blockpool network seems to be failing at the minute. 

![image](https://user-images.githubusercontent.com/44671015/150948642-3dac5c64-8eef-48fa-bd76-559051c077ad.png)

![image](https://user-images.githubusercontent.com/44671015/150948672-d381c94a-fc30-4036-828b-36831b658341.png)

Steps to reproduce
1. Go to Import Wallet
2. Select Blockpool
3. Attempt to continue

**Comment by alfonsobries** [comment]
@samharperpittam I was unable to replicate tried with `pnpm dev` and `pnpm qa`. In both cases, I was able to create and import a wallet without any error

The error from your screenshot may point to the need to use `https` but I didn't use https, so not sure what happened.

**Comment by dated** [comment]
The http / https error has been fixed with #887. The wrong network name needs to be tackled still.
