### ISSUE TITLE
[SEND Transaction] When attempting to perform SEND transaction from the the "Contacts" page, the app shows incorrect title - "Send {{ticker}}" for mainnet address

### ISSUE THREAD

**Issue by anil203** [PayvoHQ/wallet#876]
Steps to reproduce:
1. Navigate to contacts.
2. Select "SEND" option for any mainnet contact.

We'll observe that the landing page shows "Send {{ticker}}"

https://user-images.githubusercontent.com/10047242/150949109-9df6ce87-31ed-4786-9a39-e641c0a66ff4.mp4

**Comment by alfonsobries** [comment]
Fixed here https://github.com/PayvoHQ/wallet/pull/883
