### ISSUE TITLE
[Wallets] Deleting a wallet does not persist upon refresh

### ISSUE THREAD

**Issue by alesmit** [PayvoHQ/wallet#897]
### Describe the Bug

As a user, if I delete a wallet using the dropdown in the dashboard it disappears as expected. However, after refreshing the page the wallet comes back as if it was never gone.

Please see attached screenshot.

Note: the issue also happens when removal of the wallet is made through the wallet detail page.

### Expected Behavior

Refreshing the page should not bring a deleted wallet back.

### To Reproduce

![deletewallet](https://user-images.githubusercontent.com/18616324/151191256-efc23aae-9935-4075-9476-35ecc733df7a.gif)

### What operating system are you using?

macOS

### What browser are you using?

Brave (Chrome)

### What version of Node.js are you using?

16.9.1

**Comment by alfonsobries** [comment]
PR: https://github.com/PayvoHQ/wallet/issues/897 (need to be released and updated to fix the issue)
