### ISSUE TITLE
[Delete Wallet] When deleting a wallet, the confirmation pop-up does not disappear after selecting "DELETE" button. 

### ISSUE THREAD

**Issue by anil203** [PayvoHQ/wallet#907]
### Describe the Bug

When deleting a wallet, the confirmation pop-up does not disappear after selecting "DELETE" button. Further selecting the "DELETE" button again deletes the next available wallet. As a result, the user may end up deleting multiple wallets.

### Expected Behavior

After selecting the "DELETE" button, the pop-up should disappear.

### To Reproduce

1. Select the option to delete a wallet
2. From the confirmation, approve to delete by selecting the "DELETE" button
3. The confirmation pop-up still stays but the wallet is already deleted from the background
4. Selecting "DELETE" from the confirmation pop-up will delete the next available wallet.

https://user-images.githubusercontent.com/10047242/151302860-21931b97-93d7-4ec8-a0e9-20dce62c8eb5.mp4

### What operating system are you using?

macOS

### What browser are you using?

Chrome, Safari

### What version of Node.js are you using?

v14.17.6

**Comment by alfonsobries** [comment]
Fixed here https://github.com/PayvoHQ/wallet/pull/915
