### ISSUE TITLE
[Delete Wallet] Need to update the delete wallet modal to show the wallet name.

### ISSUE THREAD

**Issue by anil203** [PayvoHQ/wallet#912]
### Describe the feature you'd like to request

The current Delete Wallet modal does not provide any details on which wallet is being selected for deletion. Adding the wallet name would help the user know which wallet is being deleted.

### Describe the feature requirements you'd like

When the user selects a wallet for deletion, then display the wallet name that's being deleted on the delete wallet modal

Light version:
![image](https://user-images.githubusercontent.com/10047242/151338300-0f276160-28a9-4736-a45a-46ddb073244a.png)

Dark version:
![image](https://user-images.githubusercontent.com/10047242/151339157-288765e8-4391-4111-be63-69358abf6f5a.png)

**Comment by alfonsobries** [comment]
PR https://github.com/PayvoHQ/wallet/pull/915
