### ISSUE TITLE
[Ledger Wallet Import] Show progress indicator while scanning ledger wallets

### ISSUE THREAD

**Issue by goga-m** [PayvoHQ/wallet#923]
### Describe the refactor you'd like to request

As the scanning step for ledgers with many wallets takes too long (several minutes), adjust the UI to indicate the import progress instead of just showing skeletons.

## Current screen
![2022-01-28-162347_803x845_scrot](https://user-images.githubusercontent.com/22020168/151565026-ee6ba589-320b-4585-b79b-ead911584f0d.png)

Requires adjustment in SDK to provide the required info https://github.com/PayvoHQ/sdk/blob/master/packages/ark/source/ledger.service.ts#L54

**Comment by alfonsobries** [comment]
@goga-m do we have a design for this or something I can use as a reference? (already checked Figma and didn't find anything)

**Comment by goga-m** [comment]
@alfonsobries a toast will be shown that will indicate the number of loaded wallets:

![2022-02-01-170319_1471x961_scrot](https://user-images.githubusercontent.com/22020168/151993995-6283557a-859e-4d34-b646-4916a86e924b.png)

**Comment by alfonsobries** [comment]
@goga-m do you have a plan for the adjustment needed in the SDK, I was thinking of accepting a closure in the `options` parameter that we can use to send the wallet list (or the recently added wallet) inside the while loop. What do you think?
